apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end-deployment
  namespace: back
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: back-end
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
      - name: back-container
        image: goodbirdacr.azurecr.io/medicine/back:latest
        ports:
        - containerPort: 8080
