apiVersion: v1
kind: Service

metadata:
  name: back-end-service
  namespace: back
spec:
  selector:
    app: back-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort